#!/bin/bash

SPINDLE_HOME="$HOME/bin/spindle"
FILENAME=${2##*/}

if [ -e $1 ] ; then
	echo
	echo 'Usage: autospindle /path/to/workdir /path/to/stage4-script'
	exit 1
fi


errortest(){
	if [ $? != 0 ] ; then
		echo 'The spindle script created an error, will now exit!'
		exit 1
	fi
}

cd "$SPINDLE_HOME"
	errortest
sudo ./setup_spindle_environment "$1"
	errortest
sudo modprobe nbd max_part=16
	errortest
schroot -c spindle
	errortest
if [ `qemu --version | awk '{print $4}' | tr -d ',' != '1.0,1' ] ; then 
	sudo ./downgrade_qemu
	errortest
fi

for i in './wheezy-stage0' './wheezy-stage1' './wheezy-stage2' './wheezy-stage3' ; do
	if [ $? = 0 ] ; then
		$i
	else
		echo "ERROR while executing $i, will now quit!"
		exit 1
	fi	
done

if [ -e $2 ] ; then
	echo '==> No stage4 given, building basic system only....'
else
	./wheezy-stage4-lxde
fi

./helper export_image_for_release out/"$FILENAME".qed "$FILENAME".img

if [ $? = 0 ] ; then
	echo ; echo "Your Raspi image is ready in $SPINDLE_HOME/out/"$FILENAME".img"
	exit 0
else
	echo ; echo 'Spindle has failed to create the image, please find out what went wrong and try again.'
	exit 1
fi

exit $?
