#!/bin/bash

SPINDLE_HOME="$HOME/bin/spindle"
FILENAME=${2##*/}

if [ -e $1 ] ; then
	echo
	echo 'Usage: autospindle /path/to/workdir /path/to/stage4-script'
	exit 1
fi


errortest(){
	if [ $? != 0 ] ; then
		echo 'The spindle script created an error, will now exit!'
		exit 1
	fi
}

cd "$SPINDLE_HOME"
	errortest
sudo ./setup_spindle_environment "$1"
	errortest
sudo modprobe nbd max_part=16
	errortest
if [ -e $2 ] ; then
	echo 'No stage4 script given, will continue without...'
else
	if [ -f "$2" ] ; then 
		echo 'Copying stage4 script to chroot...'
		cp -v "$2" "$1"/$HOME/bin/spindle/
	else
		echo 'given stage4 script not found, assuming the script is in the chroot environment in spindles path!'
		echo 'if not please create the script in the next step.'
	fi
fi
echo ; echo 'You will now enter the spindle chroot environment where you can make manual changes.' 
echo 'Type exit when done making changes to continue building your image.'
echo
schroot -c spindle
	errortest
if [ `qemu --version | awk '{print $4}' | tr -d ','` != '1.0,1' ] ; then 
	schroot -c spindle sudo downgrade_qemu
	errortest
fi

for i in 'wheezy-stage0' 'wheezy-stage1' 'wheezy-stage2' 'wheezy-stage3' ; do
	if [ $? = 0 ] ; then
		echo
		echo "	 Will Now Start Executing: $i"
		echo
		schroot -c spindle $i
	else
		echo "ERROR while executing $i, will now quit!"
		exit 1
	fi
done

if [ -e $2 ] ; then
	echo '==> No stage4 given, building basic system only....'
else
	schroot -c spindle "$FILENAME"
fi

if [ -e "$2" ] ; then
	FILENAME="stage3"
fi

schroot -c spindle helper export_image_for_release out/"$FILENAME".qed "$FILENAME".img

if [ $? = 0 ] ; then
	echo ; echo "Your Raspi image is ready in $1/$HOME/out/$FILENAME.img"
	exit 0
else
	echo ; echo 'Spindle has failed to create the image, please find out what went wrong and try again.'
	exit 1
fi

exit $?
